name: Update Project Manifest

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'project-manifest.yaml'
  workflow_dispatch:

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PyYAML
        run: python -m pip install --quiet PyYAML
      - name: Generate manifest
        run: python scripts/generate_manifest.py
      - name: Commit & push if changed
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: auto-update project-manifest.yaml'
          add: 'project-manifest.yaml'
          default_author: github_actions
